version: "3"
services:
  apserver:
    build: ./apserver
    container_name: "ruby"
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./apserver:/usr/src
    ports:
      - "3000:3000"
