version: "3"
services:
  apserver:
    build:
      context: ./apserver
      target: development
    container_name: "ruby"
    tty: true
    entrypoint: /usr/src/docker-entrypoint
    volumes:
      - ./apserver:/usr/src
    ports:
      - "8080:8080"
  webserver:
    #build: ./webserver
    build:
      context: ./webserver
      target: development
    container_name: nuxt3
    tty: true
    volumes:
      - ./webserver/myapp:/usr/src/app/myapp
      - /usr/src/app/myapp/node_modules
    ports:
      - "3000:3000"
      - '24678:24678'
  loadbalancer:
    image: nginx:1.22-bullseye
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer:/etc/nginx/conf.d:ro
  dbserver:
    build: ./dbserver
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoproject
      MYSQL_USER: rubyMySql1
      MYSQL_PASSWORD: rubyMySql1
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - ./dbserver/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
