version: 0.2

env:
  variables:
    AWS_REGION: ap-northeast-1
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - WEB_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_WEB_REPOSITORY
      - API_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_API_REPOSITORY
  build:
    commands:
      - cp terraform/template/web_appspec.yml $CODEBUILD_SRC_DIR/BuildArtifact1/appspec.yml
      - cp terraform/template/api_appspec.yml $CODEBUILD_SRC_DIR/BuildArtifact2/appspec.yml
      - cd $CODEBUILD_SRC_DIR/BuildArtifact1
      - $(aws ecs describe-task-definition --task-definition $ECS_WEB_TASK_DEFINITION_ARN --query taskDefinition | jq '.containerDefinitions[0].image="<IMAGE1_NAME>"' > taskdef.json)
      - printf '{"Version":"1.0","ImageURI":"%s"}' $WEB_REPOSITORY_URI:$IMAGE_TAG > imageDetail.json

      - cd $CODEBUILD_SRC_DIR/BuildArtifact2
      - printf '{"Version":"1.0","ImageURI":"%s"}' $API_REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      - $(aws ecs describe-task-definition --task-definition $ECS_API_TASK_DEFINITION_ARN --query taskDefinition | jq '.containerDefinitions[0].image="<IMAGE1_NAME>"' > taskdef.json)

artifacts:
  files:
    - "**.*"
  secondary-artifacts:
    artifact1:
      base-directory: $CODEBUILD_SRC_DIR/BuildArtifact1
      files:
        - appspec.yml
        - taskdef.json
        - imageDetail.json
      name: BuildArtifact1
    artifact2:
      base-directory: $CODEBUILD_SRC_DIR/BuildArtifact2
      files:
        - appspec.yml
        - taskdef.json
        - imageDetail.json
      name: BuildArtifact2
