variable "app_name" {}
variable "web_app_name" {}
variable "api_app_name" {}
variable "apserver_sg_id" {}
variable "subnet_p1a_id" {}
variable "webserver_sg_id" {}
variable "subnet_p1c_id" {}
variable "ecs_main_role" {}
variable "db_endpoint" {}
variable "db_name" {}
variable "db_username" {}
variable "db_password" {}
variable "web_ports" {}
variable "api_ports" {}
variable "http_arn" {}
variable "api_blue_arn" {}
variable "web_blue_arn" {}
variable "api_green_arn" {}
variable "web_green_arn" {}
variable "api_repository_url" {}
variable "web_repository_url" {}
data "aws_caller_identity" "self" {}
