variable "app_name" {}
variable "subnet_p1a_id" {}
variable "subnet_p1c_id" {}
variable "alb_sg_id" {}
variable "s3_bucket_id" {}
variable "web_app_name" {}
variable "api_app_name" {}
variable "main_vpc_id" {}
variable "web_ports" {}
variable "api_ports" {}
