default: &default
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['HOST'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  database: <%= ENV['DBNAME'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
